print("Hello World")
print("Hello Git")
a = input("Рядок запрошення: ")
print(a + "Iryna")
age = int(input("How old are you? "))
num = int(input('скок лет?'))
print(num)

name = input("What is your name? ")
print(f"Hello {name}")